<?php
/**
 * includes/traducciones.php
 * Sistema de traducción multilenguaje (ES/PT)
 */

/**
 * Traduce una cadena al idioma actual del usuario.
 * Si la clave no existe, devuelve el texto original.
 */
function traducir($texto) {
    static $traducciones = null;
    
    if ($traducciones === null) {
        $traducciones = [
            'es' => [
                // ===== General / Nav =====
                'Dashboard' => 'Dashboard',
                'Proyectos' => 'Proyectos',
                'Productos' => 'Productos',
                'Categorias' => 'Categorías',
                'Usuarios' => 'Usuarios',
                'Cerrar Sesión' => 'Cerrar Sesión',
                'Bienvenido' => 'Bienvenido',
                'Buscar' => 'Buscar',
                'Buscar...' => 'Buscar...',
                'Filtrar' => 'Filtrar',
                'Limpiar' => 'Limpiar',
                'Volver' => 'Volver',
                'Editar' => 'Editar',
                'Eliminar' => 'Eliminar',
                'Ver' => 'Ver',
                'Guardar' => 'Guardar',
                'Actualizar' => 'Actualizar',
                'Crear' => 'Crear',
                'Cancelar' => 'Cancelar',
                'Agregar' => 'Agregar',
                'Acciones' => 'Acciones',
                'Estado' => 'Estado',
                'Nombre' => 'Nombre',
                'Descripción' => 'Descripción',
                'Descripcion' => 'Descripción',
                'Cantidad' => 'Cantidad',
                'Unidad' => 'Unidad',
                'Fecha' => 'Fecha',
                'Fecha Inicio' => 'Fecha Inicio',
                'Fecha Fin' => 'Fecha Fin',
                'Fecha Aprobación' => 'Fecha Aprobación',
                'Fecha Requerida' => 'Fecha Requerida',
                'Todas las categorias' => 'Todas las categorías',
                'Todos los estados' => 'Todos los estados',
                'No hay proyectos' => 'No hay proyectos',
                'No hay items en este proyecto' => 'No hay items en este proyecto',
                'No hay historial' => 'No hay historial',
                'No hay productos registrados' => 'No hay productos registrados',
                'Sin categoría' => 'Sin categoría',
                'y seleccionar' => 'y seleccionar',
                // ===== Categorías =====
                'Nueva Categoría' => 'Nueva Categoría',
                'Editar Categoría' => 'Editar Categoría',
                'Categoría en uso' => 'Categoría en uso',
                'No se puede eliminar' => 'No se puede eliminar',
                'productos' => 'productos',
                
                // ===== Login =====
                'Iniciar Sesión' => 'Iniciar Sesión',
                'Usuario' => 'Usuario',
                'Contraseña' => 'Contraseña',
                'Usuario o contraseña incorrectos' => 'Usuario o contraseña incorrectos',
                'Por favor, ingrese usuario y contraseña' => 'Por favor, ingrese usuario y contraseña',
                
                // ===== Proyectos =====
                'Crear Proyecto' => 'Crear Proyecto',
                'Editar Proyecto' => 'Editar Proyecto',
                'Ver Proyecto' => 'Ver Proyecto',
                'Nombre del Proyecto' => 'Nombre del Proyecto',
                'Total Proyectos' => 'Total Proyectos',
                'Últimos Proyectos' => 'Últimos Proyectos',
                'Items Pendientes' => 'Items Pendientes',
                'Items del Proyecto' => 'Items del Proyecto',
                'Agregar Item' => 'Agregar Item',
                'Orden Compra' => 'Orden Compra',
                'Número de Orden de Compra' => 'Número de Orden de Compra',
                'Orden de Compra' => 'Orden de Compra',
                'Creado por' => 'Creado por',
                'Creación' => 'Creación',
                'Historial' => 'Historial',
                'Cambio' => 'Cambio',
                'Comentario' => 'Comentario',
                '¿Está seguro?' => '¿Está seguro?',
                '¿Está seguro de que desea eliminar este elemento?' => '¿Está seguro de que desea eliminar este elemento?',
                'Ini' => 'Ini',
                'Fin' => 'Fin',
                'Apr' => 'Apr',
                'Inicio' => 'Inicio',
                'Mostrando' => 'Mostrando',
                'proyecto(s)' => 'proyecto(s)',
                'Items' => 'Items',
                'Pendientes' => 'Pendientes',
                'Llegaron' => 'Llegaron',
                
                // ===== Estados de Proyecto =====
                'Solicitado' => 'Solicitado',
                'Orçado' => 'Orçado',
                'Pendente por Aprovação' => 'Pendiente por Aprobación',
                'Aprovado por Cliente' => 'Aprobado por Cliente',
                'A espera de Orden de Compra' => 'A espera de Orden de Compra',
                'Comprando Materiales' => 'Comprando Materiales',
                'Elaboración' => 'Elaboración',
                'Terminado' => 'Terminado',
                'Pendiente por Cobro' => 'Pendiente por Cobro',
                'Finalizado' => 'Finalizado',
                
                // ===== Estados de Item =====
                'Pendiente' => 'Pendiente',
                'En Stock' => 'En Stock',
                'Cotación' => 'Cotación',
                'Pendiente por Pago' => 'Pendiente por Pago',
                'Comprado por Llegar' => 'Comprado por Llegar',
                'Llegó' => 'Llegó',
                
                // ===== Productos =====
                'Crear nuevo producto' => 'Crear nuevo producto',
                'Crear Producto' => 'Crear Producto',
                'Editar Producto' => 'Editar Producto',
                'Nuevo Producto' => 'Nuevo Producto',
                'Código / Referencia' => 'Código / Referencia',
                'Código' => 'Código',
                'Unidad de medida' => 'Unidad de medida',
                
                // ===== Usuarios =====
                'Crear Usuario' => 'Crear Usuario',
                'Editar Usuario' => 'Editar Usuario',
                'Nuevo Usuario' => 'Nuevo Usuario',
                'Nombre Completo' => 'Nombre Completo',
                'Email' => 'Email',
                'Tipo' => 'Tipo',
                'Idioma' => 'Idioma',
                'Activo' => 'Activo',
                'Inactivo' => 'Inactivo',
                'Tipo de Usuario' => 'Tipo de Usuario',
                'Idioma Preferido' => 'Idioma Preferido',
                'Nueva Contraseña' => 'Nueva Contraseña',
                'Usuario Activo' => 'Usuario Activo',
                'Directivo' => 'Directivo',
                'Gerenciador' => 'Gerenciador',
                'Supervisor' => 'Supervisor',
                'Compras' => 'Compras',
                'Proyectista' => 'Proyectista',
                
                // ===== Modal =====
                'Agregar Item al Proyecto' => 'Agregar Item al Proyecto',
                'Buscar producto en el catálogo' => 'Buscar producto en el catálogo',
                'Detalles del item' => 'Detalles del item',
                'Items agregados' => 'Items agregados',
                'Seleccionar' => 'Seleccionar',
                'Producto seleccionado' => 'Producto seleccionado',
                'Especificaciones / Notas' => 'Especificaciones / Notas',
                'Agregar a la lista' => 'Agregar a la lista',
                'Guardar todos los items' => 'Guardar todos los items',
                'Aún no ha agregado items' => 'Aún no ha agregado items',
                'Escriba para buscar productos...' => 'Escriba para buscar productos...',
                'No se encontraron productos' => 'No se encontraron productos',
                
                // ===== Confirmaciones =====
                '¿Eliminar este item?' => '¿Eliminar este item?',
                '¿Eliminar usuario?' => '¿Eliminar usuario?',
                '¿Eliminar producto?' => '¿Eliminar producto?',

                // ===== Reportes =====
                'Reporte' => 'Reporte',
                'Reportes' => 'Reportes',
                'Items por Estado' => 'Items por Estado',
                'Reporte de Entrega' => 'Reporte de Entrega',
                'Reporte de Costos' => 'Reporte de Costos',
                'Editar Costos' => 'Editar Costos',
                'Imprimir' => 'Imprimir',
                'Costo' => 'Costo',
                'Costo Unit.' => 'Costo Unit.',
                'Subtotal' => 'Subtotal',
                'Proveedor' => 'Proveedor',
                'Moneda' => 'Moneda',
                'Nº Factura' => 'Nº Factura',
                'Fecha Compra' => 'Fecha Compra',
                'Entregado' => 'Entregado',
                'Recibido' => 'Recibido',
                'Responsable de la Entrega' => 'Responsable de la Entrega',
                'Responsable de la Recepción' => 'Responsable de la Recepción',
                'Departamento de Compras' => 'Departamento de Compras',
                'Operador del Proyecto' => 'Operador del Proyecto',
                'Total' => 'Total',
                'Total General' => 'Total General',
                'Resumen General' => 'Resumen General',
                'Costos por Estado' => 'Costos por Estado',
                'Costos por Categoría' => 'Costos por Categoría',
                'Detalle por Item' => 'Detalle por Item',
                'Materiales Entregados' => 'Materiales Entregados',
                'Materiales en Tránsito' => 'Materiales en Tránsito',
                'Emitido el' => 'Emitido el',
                'Documento sin valor fiscal' => 'Documento sin valor fiscal',

                // ===== Notificaciones =====
                'Notificaciones' => 'Notificaciones',
                'Marcar todas' => 'Marcar todas',
                'Marcar todas como leídas' => 'Marcar todas como leídas',
                'Ver todos los proyectos' => 'Ver todos los proyectos',
                'Cargando' => 'Cargando',
                'No tienes notificaciones' => 'No tienes notificaciones',
                'Todo está al día' => 'Todo está al día',
                'Error al cargar notificaciones' => 'Error al cargar notificaciones',



            ],
            'pt' => [
                // ===== General / Nav =====
                'Dashboard' => 'Painel',
                'Proyectos' => 'Projetos',
                'Productos' => 'Produtos',
                'Categorias' => 'Categorias',
                'Usuarios' => 'Usuários',
                'Cerrar Sesión' => 'Sair',
                'Bienvenido' => 'Bem-vindo',
                'Buscar' => 'Buscar',
                'Buscar...' => 'Buscar...',
                'Filtrar' => 'Filtrar',
                'Limpiar' => 'Limpar',
                'Volver' => 'Voltar',
                'Editar' => 'Editar',
                'Eliminar' => 'Excluir',
                'Ver' => 'Ver',
                'Guardar' => 'Salvar',
                'Actualizar' => 'Atualizar',
                'Crear' => 'Criar',
                'Cancelar' => 'Cancelar',
                'Agregar' => 'Adicionar',
                'Acciones' => 'Ações',
                'Estado' => 'Status',
                'Nombre' => 'Nome',
                'Descripción' => 'Descrição',
                'Descripcion' => 'Descrição',
                'Cantidad' => 'Quantidade',
                'Unidad' => 'Unidade',
                'Fecha' => 'Data',
                'Fecha Inicio' => 'Data de Início',
                'Fecha Fin' => 'Data de Término',
                'Fecha Aprobación' => 'Data de Aprovação',
                'Fecha Requerida' => 'Data Requerida',
                'Todas las categorias' => 'Todas as categorias',
                'Todos los estados' => 'Todos os status',
                'No hay proyectos' => 'Não há projetos',
                'No hay items en este proyecto' => 'Não há itens neste projeto',
                'No hay historial' => 'Não há histórico',
                'No hay productos registrados' => 'Não há produtos cadastrados',
                'Sin categoría' => 'Sem categoria',
                'y seleccionar' => 'e selecionar',
                'Nueva Categoría' => 'Nova Categoria',
                'Editar Categoría' => 'Editar Categoria',
                'Categoría en uso' => 'Categoria em uso',
                'No se puede eliminar' => 'Não é possível excluir',
                'productos' => 'produtos',
                                
                // ===== Login =====
                'Iniciar Sesión' => 'Entrar',
                'Usuario' => 'Usuário',
                'Contraseña' => 'Senha',
                'Usuario o contraseña incorrectos' => 'Usuário ou senha incorretos',
                'Por favor, ingrese usuario y contraseña' => 'Por favor, insira usuário e senha',
                
                // ===== Proyectos =====
                'Crear Proyecto' => 'Criar Projeto',
                'Editar Proyecto' => 'Editar Projeto',
                'Ver Proyecto' => 'Ver Projeto',
                'Nombre del Proyecto' => 'Nome do Projeto',
                'Total Proyectos' => 'Total de Projetos',
                'Últimos Proyectos' => 'Últimos Projetos',
                'Items Pendientes' => 'Itens Pendentes',
                'Items del Proyecto' => 'Itens do Projeto',
                'Agregar Item' => 'Adicionar Item',
                'Orden Compra' => 'Ordem de Compra',
                'Número de Orden de Compra' => 'Número da Ordem de Compra',
                'Orden de Compra' => 'Ordem de Compra',
                'Creado por' => 'Criado por',
                'Creación' => 'Criação',
                'Historial' => 'Histórico',
                'Cambio' => 'Mudança',
                'Comentario' => 'Comentário',
                '¿Está seguro?' => 'Tem certeza?',
                '¿Está seguro de que desea eliminar este elemento?' => 'Tem certeza de que deseja excluir este item?',
                'Ini' => 'Iníc',
                'Fin' => 'Fim',
                'Apr' => 'Apr',
                'Inicio' => 'Início',
                'Mostrando' => 'Mostrando',
                'proyecto(s)' => 'projeto(s)',
                'Items' => 'Itens',
                'Pendientes' => 'Pendentes',
                'Llegaron' => 'Chegaram',
                
                // ===== Estados de Proyecto =====
                'Solicitado' => 'Solicitado',
                'Orçado' => 'Orçado',
                'Pendente por Aprovação' => 'Pendente por Aprovação',
                'Aprovado por Cliente' => 'Aprovado pelo Cliente',
                'A espera de Orden de Compra' => 'Aguardando Ordem de Compra',
                'Comprando Materiales' => 'Comprando Materiais',
                'Elaboración' => 'Elaboração',
                'Terminado' => 'Terminado',
                'Pendiente por Cobro' => 'Pendente de Cobrança',
                'Finalizado' => 'Finalizado',
                
                // ===== Estados de Item =====
                'Pendiente' => 'Pendente',
                'En Stock' => 'Em Estoque',
                'Cotación' => 'Cotação',
                'Pendiente por Pago' => 'Pendente de Pagamento',
                'Comprado por Llegar' => 'Comprado a Chegar',
                'Llegó' => 'Chegou',
                
                // ===== Productos =====
                'Crear nuevo producto' => 'Criar novo produto',
                'Crear Producto' => 'Criar Produto',
                'Editar Producto' => 'Editar Produto',
                'Nuevo Producto' => 'Novo Produto',
                'Código / Referencia' => 'Código / Referência',
                'Código' => 'Código',
                'Unidad de medida' => 'Unidade de medida',
                
                // ===== Usuarios =====
                'Crear Usuario' => 'Criar Usuário',
                'Editar Usuario' => 'Editar Usuário',
                'Nuevo Usuario' => 'Novo Usuário',
                'Nombre Completo' => 'Nome Completo',
                'Email' => 'E-mail',
                'Tipo' => 'Tipo',
                'Idioma' => 'Idioma',
                'Activo' => 'Ativo',
                'Inactivo' => 'Inativo',
                'Tipo de Usuario' => 'Tipo de Usuário',
                'Idioma Preferido' => 'Idioma Preferido',
                'Nueva Contraseña' => 'Nova Senha',
                'Usuario Activo' => 'Usuário Ativo',
                'Directivo' => 'Diretivo',
                'Gerenciador' => 'Gerente',
                'Supervisor' => 'Supervisor',
                'Compras' => 'Compras',
                'Proyectista' => 'Projetista',
                
                // ===== Modal =====
                'Agregar Item al Proyecto' => 'Adicionar Item ao Projeto',
                'Buscar producto en el catálogo' => 'Buscar produto no catálogo',
                'Detalles del item' => 'Detalhes do item',
                'Items agregados' => 'Itens adicionados',
                'Seleccionar' => 'Selecionar',
                'Producto seleccionado' => 'Produto selecionado',
                'Especificaciones / Notas' => 'Especificações / Notas',
                'Agregar a la lista' => 'Adicionar à lista',
                'Guardar todos los items' => 'Salvar todos os itens',
                'Aún no ha agregado items' => 'Ainda não adicionou itens',
                'Escriba para buscar productos...' => 'Digite para buscar produtos...',
                'No se encontraron productos' => 'Nenhum produto encontrado',
                
                // ===== Confirmaciones =====
                '¿Eliminar este item?' => 'Excluir este item?',
                '¿Eliminar usuario?' => 'Excluir usuário?',
                '¿Eliminar producto?' => 'Excluir produto?',

                // ===== Reportes =====
                'Reporte' => 'Relatório',
                'Reportes' => 'Relatórios',
                'Items por Estado' => 'Itens por Status',
                'Reporte de Entrega' => 'Relatório de Entrega',
                'Reporte de Costos' => 'Relatório de Custos',
                'Editar Costos' => 'Editar Custos',
                'Imprimir' => 'Imprimir',
                'Costo' => 'Custo',
                'Costo Unit.' => 'Custo Unit.',
                'Subtotal' => 'Subtotal',
                'Proveedor' => 'Fornecedor',
                'Moneda' => 'Moeda',
                'Nº Factura' => 'Nº Fatura',
                'Fecha Compra' => 'Data Compra',
                'Entregado' => 'Entregue',
                'Recibido' => 'Recebido',
                'Responsable de la Entrega' => 'Responsável pela Entrega',
                'Responsable de la Recepción' => 'Responsável pelo Recebimento',
                'Departamento de Compras' => 'Setor de Compras',
                'Operador del Proyecto' => 'Operador do Projeto',
                'Total' => 'Total',
                'Total General' => 'Total Geral',
                'Resumen General' => 'Resumo Geral',
                'Costos por Estado' => 'Custos por Status',
                'Costos por Categoría' => 'Custos por Categoria',
                'Detalle por Item' => 'Detalhamento por Item',
                'Materiales Entregados' => 'Materiais Entregues',
                'Materiales en Tránsito' => 'Materiais em Trânsito',
                'Emitido el' => 'Emitido em',
                'Documento sin valor fiscal' => 'Documento sem valor fiscal',

                // ===== Notificaciones =====
                'Notificaciones' => 'Notificações',
                'Marcar todas' => 'Marcar todas',
                'Marcar todas como leídas' => 'Marcar todas como lidas',
                'Ver todos los proyectos' => 'Ver todos os projetos',
                'Cargando' => 'Carregando',
                'No tienes notificaciones' => 'Você não tem notificações',
                'Todo está al día' => 'Tudo em dia',
                'Error al cargar notificaciones' => 'Erro ao carregar notificações',

            ]
        ];
    }
    
    $idioma = $_SESSION['idioma'] ?? 'es';
    return $traducciones[$idioma][$texto] ?? $texto;
}